sources:
  - name: dummyjson_api_raw
    description: "Data ingested from DummyJSON API via AWS Lambda"
    database: awsdatacatalog
    schema: analytics_dev # Must match Glue Database name
    loader: aws_lambda # Helps with lineage documentation

    tables:
      - name: products_raw
        identifier: products # The ACTUAL name in the Glue Catalog
        description: "Raw products data in S3/Bronze layer"
        columns:
          - name: id
            description: "Primary key from API"
            tests:
              - unique
              - not_null
